#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod address;
pub mod context;
pub mod ecdsa;
pub mod erc1967_proxy;
pub mod erc1967_upgrade;
pub mod erc20;
pub mod erc20_mock;
pub mod ethereum_utxo;
pub mod globals;
pub mod i_beacon;
pub mod ierc1822_proxiable;
pub mod ierc20;
pub mod ierc20_metadata;
pub mod iutxo;
pub mod math;
pub mod paginator;
pub mod proxy;
pub mod shared_types;
pub mod storage_slot;
pub mod strings;
pub mod type_caster;
pub mod utxo_array;
pub mod vector;
